### ISSUE TITLE
the float datatype 

### ISSUE THREAD

**Issue by AvailableCXGuo** [GPUPeople/spECK#11] opened 2023-07-18 07:21 UTC
Can I know how to use spECK for float datatype with right output results?

**Comment by dabeschte** [comment] 2023-07-18 07:56
The library compiles for float and double by default. You just have to select the correct template. 

If you use our command line interface, uncomment the [`Executor<float>` and comment out the double version](https://github.com/GPUPeople/spECK/blob/2f84623087d536b5ae6e71d08db754941f60667a/source/runspECK.cpp#L29C11-L29C11). Or just replace double by float. 

If you use the library inside you application, just call `MultiplySpeck` with [float as the first template parameter](https://github.com/GPUPeople/spECK/blob/2f84623087d536b5ae6e71d08db754941f60667a/source/Executor.cpp#L48).

**Comment by AvailableCXGuo** [comment] 2023-07-18 08:08
I replace the double by float in runspECK.cpp:29 and Executor.cpp:84, and I set the CompareResult to true in config.ini. But i got the "Error: Matrix incorrect".

**Comment by dabeschte** [comment] 2023-07-18 09:01
can you give me an example matrix that does not work for you?
because mine works just fine. I tried out [this matrix](https://sparse.tamu.edu/HB/1138_bus).

To reproduce my results: I used cuda11 branch, uncommented [this line](https://github.com/GPUPeople/spECK/blob/31f0203ff3bf13b5583b7d5e5d226a4ba6030f4a/source/Executor.cpp#L83) and changed double to float in [this line](https://github.com/GPUPeople/spECK/blob/31f0203ff3bf13b5583b7d5e5d226a4ba6030f4a/source/runspECK.cpp#L31).

I did not change anything else

**Comment by AvailableCXGuo** [comment] 2023-07-18 09:08
I tried the 1138_bus.mtx and it works. The matrix I use for testing is c-66.mtx. Should be found in the same collection.

**Comment by dabeschte** [comment] 2023-07-18 09:13
c-66.mtx works too on my system. are you sure that you did not change anything else?
are you also using the cuda 11 branch?

**Comment by dabeschte** [comment] 2023-07-18 09:15
ah, did you enable the value comparisons? maybe my values are incorrect. let me check

**Comment by dabeschte** [comment] 2023-07-18 09:47
I updated the cuda11 branch so that you can use the [compareData variable](https://github.com/GPUPeople/spECK/blob/be5bac58e7f8eee45e727d3ab5a4d5bfbdce9823/source/Executor.cpp#L27) to enable or disable value comparison. but be careful, because value comparison is not always reliable. we currently only validate relative errors, but the could be huge for very small values.

I assume that the problem you faced was that the values of the reference matrix were deleted to save some memory (line 37).
Let me know if that fixed it for you

**Comment by AvailableCXGuo** [comment] 2023-07-19 06:51
I set the compareData to true. It weird that the results are incorrect on my V100 system(CUDA 11.7) with the updated cuda-11 branch, but I got a correct on my A100 system(CUDA 12.01). To some extent, I think my problem is already solved. Thanks for your patience.

**Comment by dabeschte** [comment] 2023-07-19 07:14
That's really strange, but unfortunately difficult for me to debug, because I only have a 3080 and a 1080 ti to run the code on.
If, by any chance, you get to the bottom of this, please let me know, so I can fix it.

I am glad that I could help. I will close this issue for now

**Closed as completed by dabeschte** 2023-07-19 07:14 UTC
